version: '3.1'

services:

  app:
    build: .
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
      - DD_ENV=juice
      - DD_APPSEC_ENABLED=true
      - NODE_ENV=ctf
    env_file:
      - ./.env
    depends_on:
      - datadog-agent
      - db
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    restart: on-failure

  datadog-agent:
    image: datadog/agent
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
      - SYS_PTRACE
      - NET_ADMIN
      - IPC_LOCK
    environment:
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE=name:datadog-agent
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_COMPLIANCE_CONFIG_ENABLED=true
      - DD_RUNTIME_SECURITY_CONFIG_ENABLED=true
      - DD_SYSTEM_PROBE_ENABLED=true
      - DD_ENV=juice
      - HOST_ROOT=/host/root
    env_file:
      - ./.env
    ports:
      - "8126:8126"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /etc/passwd:/etc/passwd:ro 
      - /etc/os-release:/host/etc/os-release:ro
      - /etc/group:/etc/group:ro
      - /sys/kernel/debug:/sys/kernel/debug
      - /:/host/root:ro

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: juiceshop
      MYSQL_USER: dev
      MYSQL_PASSWORD: example
    healthcheck:
      test: "mysqladmin -u root -pexample ping"
      interval: 2s
      retries: 60     
